# Generated by Django 4.2.6 on 2024-02-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='India',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ind_state', models.CharField(max_length=100)),
                ('Ind_city', models.CharField(max_length=100)),
                ('Ind_code', models.IntegerField()),
            ],
        ),
    ]
